### ISSUE TITLE
`image` name in docker-compose.yml leading to errors

### ISSUE THREAD

**Issue by shauryapednekar** [timalander/garmin-gpt-summary#2]
Hi, I tried following the steps in the How to Run section, but am running issues with `docker compose up`.

For the placeholders in the `docker-compose.yml` file, I set the `image:` value to `test_image_name` following the instructions that state "The `image:` name can be anything you want.".

However, I get the following error:
```zsh
% docker compose up
[+] Running 1/1
 ✘ api Error                                                                                   1.5s 
Error response from daemon: pull access denied for test_image_name, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

I haven't used docker/docker-compose too much before - am I misunderstanding the instructions?

Here's my docker-compose.yml file:
```yml
version: '3.8'
services:
  api:
    image: test_image_name
    environment:
      - OPENAI_API_KEY
      - MAILGUN_API_KEY
      - GARMIN_SUMMARY_DB_PATH
      - TO_EMAIL
      - FROM_EMAIL
      - FROM_EMAIL_DOMAIN
    ports:
      - '8001:8001'
    networks:
      - default
    volumes:
      - /data/DBs:/data

networks:
  default:
    driver: bridge
```
